### ISSUE TITLE
Plugin installed but not seen anywhere

### ISSUE THREAD

**Issue by drone-ah** [de-jcup/eclipse-yaml-editor#60]
Hi,

I installed this plugin (in two different versions of eclipse) and it seemed to have no effect. .yml files continue to load in the default text editor. Right clicking on the file and going to open with does not present me with any new options. Furthermore, when I go to Open With -> Other... There are no options for YML files.

Any suggestions to help resolve this will be appreciated.

Shri

**Comment by de-jcup** [comment]
Hello @drone-ah ,

please do following:

## Verify you have installed the plugin
Select `Help-> About Eclipse IDE` inside main menu. You will a similar dialog like shown in next
picture:

![image](https://user-images.githubusercontent.com/11644753/56060229-89b68b80-5d66-11e9-9826-bd50a887af4f.png)

Then press `Installation Details` button at this dialog. A details dialog appears. Type 'yaml' at the filter field and you should find Yaml Editor appearing:

![image](https://user-images.githubusercontent.com/11644753/56060354-e1ed8d80-5d66-11e9-843f-9034762ade42.png)

If Yaml Editor is not listed here the plugin installation did not work

## Plugin installation verified, still having problems
### Select default editor by  `Open with Other ...`
Filter internal editors by typing `yaml` in filter field as shown in next picture:
![image](https://user-images.githubusercontent.com/11644753/56060580-912a6480-5d67-11e9-908d-299b45bb9181.png)
If you check the last checkbox ("Use it for all `*.yml` files" ) it becomes default for all these files.
### Other way over preferences
You can achieve this also by using preferences:
Open `Window->Preferences` and enter `file as`inside filter field as shown in next picture:
![image](https://user-images.githubusercontent.com/11644753/56060889-5aa11980-5d68-11e9-9e7b-75e9f922b767.png)

If `*.yml` is not listed you are able to add it by the upper `Add..`button and add an associated editor with the lower `Add...`button. If you are not able to select `Yaml Editor` as associated editor than somethings is extreme wrong.

## I am still not able to use/call the editor
Please do `Window->Show View->Other...` and enter `error` inside upcoming dialog:
![image](https://user-images.githubusercontent.com/11644753/56061098-d1d6ad80-5d68-11e9-9d57-9a1fbd3f9bd7.png)
Select the `error log view` and search inside the log view for problems with Yaml Editor plugin (e.g.  it cannot start because of some problems etc). Please copy the stacktrace and paste it to this issue

**Comment by nivas4349** [comment]
Hi, 

I'm facing same issue and uploaded configuration [here](https://github.com/nivas4349/MyApps/blob/master/yaml-file-error.txt). This works fine in my other version of eclipse. Could you please assist me in enabling this editor?

**Comment by de-jcup** [comment]
@nivas4349 : I assume the plugin cannot be started and has problems on Eclipse startup.

Please try following. Open  `Window->Show View ->Error Log`
Then
1. clear all error logs.
2. restart your eclipse
3. open error log view again and look for entries about something starting with de.jcup.
4. please attach stacktraces etc. to the issue here, or on a linked location

**Comment by nivas4349** [comment]
@de-jcup, Surprisingly I don't see single entry related to de-jcup...

the only clue I have at this point is the [configuration](https://github.com/nivas4349/MyApps/blob/master/yaml-editor-working-config.txt) that is working for another eclipse version, if that could be of any use

**Comment by de-jcup** [comment]
Hm.. strange.

## Check installation directories
Please look into 
```
$pathToYourEclipse/eclipse/plugins
$pathToYourEclipse/eclipse/features
```
if you see any folders or jars there starting with "de.jcup"

If you do not see anyhting the installer has even not installed the plugin at all from eclipse marketplace - so it would be clear why it's not listed. So you should just install again by eclipse marketplace (and check for any errors on installation process)

## Try to uninstall
If you can see Yaml Editor in Eclipse IDE installation details but it does not work, please select it there and do an "Uninstall" operation.
After this restart your eclipse and install "Yaml Editor" again by eclipse marketplace.

**Comment by nivas4349** [comment]
I don't see de.jcup.yamleditor_1.4.2.jar in either of these 

```
$pathToYourEclipse/eclipse/plugins
$pathToYourEclipse/eclipse/features
```

but, found it in .p2⁩/pool⁩/plugins⁩

after this I re-installed as you suggested, and saw the below error

org.eclipse.equinox.p2.touchpoint.eclipse
Warning
Failed to find a configured bundleInfo for: [R]de.jcup.yamleditor 1.4.2.

**Comment by de-jcup** [comment]
I hope you have found a solution - sound like a problem with p2, means your equinox setup . I would install a complete new eclipse instance to solve the problem (and install all things by eclipse marketplace, nothing directly by filesystem).
