### ISSUE TITLE
Support Go Templates

### ISSUE THREAD

**Issue by teoincontatto** [de-jcup/eclipse-yaml-editor#76]
I see that when opening template yaml files the editor spawn an validation error. I whould like to being able to disable such validations on a project basis in order to allow use this editor for such templates (actually they a re go templates for helm).

**Comment by de-jcup** [comment]
Okay, I understand the situation (I have got this too, but currently I rename them ...). Normally I always try to avoid project specific settings, but maybe this is necessary.

What do you think about global path filters - or patterns. So something like 
`disable validation for : "**/templates/*.yaml, template*.yaml" `
inside preferences?

**Comment by teoincontatto** [comment]
Global path filters seems good and would allow to have both tamplates and plain yaml files in a project. But I still think an option to disable completely validation it is needed since this is a common case for all eclipse validations. In particular that should integrate better in eclipse validations, seems that the editor is validating only files that are opened instead. Not sure if integration with eclipse validation  is the way to go since it is probably too deep bounded with eclipse build cycle but maybe is worth some investigation.

**Comment by de-jcup** [comment]
I investigated a way to integrate into standard validation inside eclipse some time ago - as far as I remember  there is (unfortunately) a strong dependency to `WTP` (web tools platform). Also an integration to this would be ... not nice.

Wanting my plugins to work with less dependencies as possible (KISS pattern + reduce problems with other dependencies) - so I decided to setup validation in my own preferences.

Writing this... I checked the preferences of the editor... and I have currently not integrated an option to turn off globally validation for yaml files... ups.

#### Proposal
So I will provide a 
`enable validation [x]` 
inside preferences in combination with filters when validation is enabled.

Would this be suitable for your needs ?

**Comment by teoincontatto** [comment]
Yeah, that would solve my use case.

**Comment by de-jcup** [comment]
Hello @teoincontatto .

I tried to disable validation... but...

those failures are are shown, because used YAML parser (snake) complies about invalid yaml (and is right because { and } are normally used as mapping inside yaml.

Using parsed yaml nodes to create the outline ignoring the parse errors would result in empty outline view when at least one parse error occurs, because snake is not able to parse the document, so no `AST` available.

## Another approach: Go Template support
Instead of turning of validation I will provide a "Go template support" option in preferences, which is enabled per default.
At parse time the editor will inspect the content of being a go template or not (can be estimated by occurrence of `{{` and `}}` ). 

In this case the parser will not validate the origin source, but an replacement
which is valid for yaml: `{{` will be replaced by `((` and `}}` will be replaced by `((` special characters
inside will be replaced by _ inside this block.

Also syntax highlighting will be provided for templates

**Comment by de-jcup** [comment]
Before:

![image](https://user-images.githubusercontent.com/11644753/68257314-21493780-0033-11ea-8041-29833e13726c.png)
Also no outline was available.

With last changes you can enable `Support Go templates` inside preferences:
![image](https://user-images.githubusercontent.com/11644753/68257372-52296c80-0033-11ea-847f-1af5d89960aa.png)

When this has been enabled the editor file looks now like:
![image](https://user-images.githubusercontent.com/11644753/68257527-daa80d00-0033-11ea-924f-c222b54da089.png)

If the `Go template support` was doing some changes under the hood to get valid yaml there will be an information marker at the first line of the editor:

![image](https://user-images.githubusercontent.com/11644753/68257464-aaf90500-0033-11ea-97ef-707ed251dcdc.png)

Inside the outline you will see the changes - so instead of `{{ .Release.Name }}-configmap` you find a santiized value:

![image](https://user-images.githubusercontent.com/11644753/68257653-44281b80-0034-11ea-9631-e353136d4ce8.png)

**Comment by de-jcup** [comment]
When no go template parts are detected nothing has been changed and you will get also no such information marker:

![image](https://user-images.githubusercontent.com/11644753/68257770-aaad3980-0034-11ea-904d-8b4e231aa81d.png)

**Comment by de-jcup** [comment]
@teoincontatto : I think this is much better. If you have still the need to turn off validation - means parsing at all and so no outline - please create another issue.

**Comment by teoincontatto** [comment]
I'm impressed! That is way better than the initial solution of disabling validation. I'll let you know if I found any use case that requires disabling validation. Will update the plugin to try the new feature asap :)
